USE [master]
GO

/****** Object:  Database [SampleDb]    Script Date: 7/27/2024 12:24:07 PM ******/
CREATE DATABASE [SampleDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVERS\MSSQL\DATA\SampleDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SampleDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVERS\MSSQL\DATA\SampleDb_log.ldf' , SIZE = 3136KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SampleDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SampleDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SampleDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SampleDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SampleDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SampleDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SampleDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SampleDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SampleDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SampleDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SampleDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SampleDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SampleDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SampleDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SampleDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SampleDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SampleDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SampleDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SampleDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SampleDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SampleDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SampleDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SampleDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SampleDb] SET RECOVERY FULL 
GO

ALTER DATABASE [SampleDb] SET  MULTI_USER 
GO

ALTER DATABASE [SampleDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SampleDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SampleDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SampleDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SampleDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SampleDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SampleDb] SET  READ_WRITE 
GO

